# Generated by Django 4.0.1 on 2022-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('nid', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=25)),
                ('schedule', models.CharField(max_length=25)),
                ('pass1', models.CharField(max_length=25)),
                ('pass2', models.CharField(max_length=30)),
            ],
        ),
    ]
