# Generated by Django 4.0.1 on 2022-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='schedule',
        ),
        migrations.AddField(
            model_name='userform',
            name='gymtime',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
