# Generated by Django 4.0.1 on 2022-02-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_userform_schedule_userform_gymtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='gymtime',
        ),
    ]
